#!/usr/bin/env bash
# display information about subdomains.

if [ $# -eq 1 ]; then
    sub_domains='www lb-01 web-01 web-02'
else
    sub_domains="$2"
fi

for sub in $sub_domains; do
    echo -n "The subdomain $sub"
    dns_output=$(dig +short -t A "$sub.$1")

    if [ -n "$dns_output" ]; then
        record_type="A"
        destination=$(echo "$dns_output" | awk '{print $1}')
        echo " is a $record_type record and points to $destination"
    else
        echo " DNS query returned empty or an error."
    fi
done
