#!/usr/bin/env bash
# This script transfers a file to a remote server using scp.

# Assign parameters to variables
file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# Check if the correct number of parameters is provided
if [ "$#" -eq 4 ]; then
    scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path" "$username@$server_ip:~"
else
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
