#!/usr/bin/env bash
# This script configures Nginx to redirect /redirect_me to another page with a "301 Moved Permanently" status code.

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom HTML file with the redirection message
echo '<html><head><meta http-equiv="refresh" content="0;url=/new_location"></head></html>' | sudo tee /var/www/html/redirect_me.html >/dev/null

echo "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx (without using systemctl)
sudo service nginx restart

# Exit the script
exit 0
