#!/usr/bin/env bash
# This script configures Nginx with a custom X-Served-By header.

# Update package list and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Allow Nginx HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a custom index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure Nginx default site to include custom header
custom_header="add_header X-Served-By \$hostname;"
sudo sed -i "s|server_name\ _|server_name _;\n\t$custom_header|" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
