#!/usr/bin/env bash
# This script configures Nginx on a new Ubuntu machine.

# Update the package list and install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx HTTP traffic through the firewall
sudo ufw allow 'Nginx HTTP'

# Create a custom index page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Configure a custom HTTP response header
new_string="listen 80 default_server;\\n\\tlocation \/redirect_me {\\n\\t\\treturn 301 https:\/\/www.youtube.com\/;\\n\\t}\\n\\tadd_header X-Served-By \$hostname;"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html

# Configure the 404 error page
new_string2="listen 80 default_server;\\nerror_page 404 \/404.html;\\n\\tlocation = \/404.html {\\n\\t\\troot \/usr\/share\/nginx\/html;\\n\\t\\tinternal;\\n\\t}\\n\\tadd_header X-Served-By \$hostname;"
sudo sed -i "s/listen 80 default_server;/$new_string2/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart
