#!/usr/bin/env bash
# This script configures HAProxy on a new Ubuntu machine to distribute traffic to web-01 and web-02.

# Update and upgrade packages
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get update

# Install HAProxy
sudo apt-get install haproxy=2.8.\* -y

# Configure HAProxy
echo "frontend web-front
        bind *:80
        mode http
        default_backend web-backend

backend web-backend
        balance roundrobin
        server web1 100.26.167.18:80 check
        server web2 54.175.189.193:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAProxy
sudo service haproxy restart
