#!/usr/bin/env bash
# Generates a MySQL dump with all databases
# and creates a compressed archive out of it.

if [ "$1" ]; then
    touch .mylogin.cnf
    printf "[client]\nuser = %s\npassword = %s" "root" "$1" >> .mylogin.cnf
    chmod 600 .mylogin.cnf

    if mysqldump --defaults-extra-file=.mylogin.cnf --all-databases > backup.sql; then
        if tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql; then
            echo "Backup completed successfully."
        else
            echo "Failed to create the tar.gz archive."
        fi
    else
        echo "MySQL dump failed. Check your password or MySQL configuration."
    fi

    # Clean up the temporary .mylogin.cnf and backup.sql files
    rm -f .mylogin.cnf
    rm -f backup.sql
fi
