#!/usr/bin/env bash
# Display listening ports with PID and program name

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

# Display TCP listening ports with PID and program name
netstat -tulnp | grep '^tcp' | awk '{print $1, $4, $5, $6, $7}' | sed -e 's/:::/[::]:/' | while read -r line; do
    pid=$(echo "$line" | awk '{print $NF}' | cut -d '/' -f1)
    program_name=$(echo "$line" | awk '{print $NF}' | cut -d '/' -f2-)
    echo "tcp $line" | sed -e "s/$pid/$pid\/$program_name/"
done

# Display UDP listening ports with PID and program name
netstat -ulnp | grep '^udp' | awk '{print $1, $4, $5, $6, $7}' | sed -e 's/:::/[::]:/' | while read -r line; do
    pid=$(echo "$line" | awk '{print $NF}' | cut -d '/' -f1)
    program_name=$(echo "$line" | awk '{print $NF}' | cut -d '/' -f2-)
    echo "udp $line" | sed -e "s/$pid/$pid\/$program_name/"
done

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# Display UNIX domain sockets with PID and program name
netstat -ulnp | grep '^unix' | awk '{print $1, $3, $4, $5, $6, $7}' | while read -r line; do
    pid=$(echo "$line" | awk '{print $NF}' | cut -d '/' -f1)
    program_name=$(echo "$line" | awk '{print $NF}' | cut -d '/' -f2-)
    echo "unix $line" | sed -e "s/$pid/$pid\/$program_name/"
done
