#!/usr/bin/env bash
# This configures Nginx to listen on port 80.

#Remove the previous config
rm /etc/nginx/sites-enabled/default

# Configure Nginx to listen on port 80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
