#!/usr/bin/env bash
# This script displays "To infinity and beyond" indefinitely with a sleep of 2 seconds
# and prints "OK" when receiving a SIGTERM signal.

trap 'echo "OK"; exit' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
