#!/usr/bin/env bash
# This script displays the time from 0 to 12 hours and 1 to 59 minutes

hour=0
while [ $hour -<= 12 ]; do
    minute=1
    while [ $minute -le 59 ]; do
        printf "%02d:%02d\n" $hour $minute
        ((minute++))
    done
    ((hour++))
done
