#!/usr/bin/env bash
# This script configures the hosts file to set localhost to 127.0.0.2 and facebook.com to 8.8.8.8.

cp /etc/hosts ~/hosts.new
sed -i s/^127.*localhost$/127.0.0.2\ localhost/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
