#!/usr/bin/env bash
# Run Nginx as the nginx user and make it listen on port 8080

# Modify the Apache configuration to stop listening on port 8080
sed -i 's/Listen 8080/# Listen 8080/g' /etc/apache2/ports.conf

# Modify the Nginx configuration to run as the nginx user and listen on port 8080
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Modify the Nginx site configuration to listen on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

# Gracefully restart Apache (if needed) and Nginx
service apache2 restart
service nginx restart
