#!/bin/bash

# Define the server IP or hostname
server="server01"

# Define the username
username="ubuntu"

# Define the private key file
private_key="~/.ssh/school"

# Use SSH to connect to the server with the specified private key
ssh -i $private_key $username@$server
